name: demo_flutter
description: SharkSW flutter demo project for customers.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  google_fonts: ^2.3.1
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^1.0.3
  url_launcher: ^6.0.20
  web_browser: ^0.5.0
  cupertino_icons: ^1.0.4
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  mockito: ^5.1.0
  flutter_lints: ^1.0.4
  pretty_dio_logger: ^1.1.1
  dart_code_metrics: ^4.10.1


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/json/